Uganda 2019
nasaharvest/crop-mask pull request #249
Opened 2022-12-02 18:45 UTC by adebowaledaniel

2022-12-05 19:07 UTC, ivanzvonkov commented on src/models/data.py
> +            # TODO: condition for both datasets are equal
Please fix!

2022-12-05 19:08 UTC, ivanzvonkov commented on train.py
> +# train_datasets = [datasets[1].dataset]  # [d.dataset for d in datasets]
Looks like CI training time did not increase too much, I am fine with removing this line completely

2022-12-05 19:08 UTC, ivanzvonkov requested changes
Requested a couple small changes

2022-12-06 18:42 UTC, adebowaledaniel commented
It seems there is an exemption to the `HawaiiAgriculturalLandUse2020` dataset you just added; see the [failed test ](https://github.com/nasaharvest/crop-mask/actions/runs/3632110310/jobs/6127575244#step:15:419)

2023-03-01 14:58 UTC, ivanzvonkov commented on src/models/data.py
> +            elif local_crop > local_non_crop:
👍 👍

2023-03-01 15:09 UTC, ivanzvonkov approved these changes
Looks good, if tests pass, good to merge

2023-03-23 22:26 UTC, merged